
import { BookInfo } from './types';

export const OLD_TESTAMENT: BookInfo[] = [
  { id: 'Genesis', name: 'Gênesis', apiName: 'Gênesis', chapters: 50 },
  { id: 'Exodus', name: 'Êxodo', apiName: 'Êxodo', chapters: 40 },
  { id: 'Leviticus', name: 'Levítico', apiName: 'Levítico', chapters: 27 },
  { id: 'Numbers', name: 'Números', apiName: 'Números', chapters: 36 },
  { id: 'Deuteronomy', name: 'Deuteronômio', apiName: 'Deuteronômio', chapters: 34 },
  { id: 'Joshua', name: 'Josué', apiName: 'Josué', chapters: 24 },
  { id: 'Judges', name: 'Juízes', apiName: 'Juízes', chapters: 21 },
  { id: 'Ruth', name: 'Rute', apiName: 'Rute', chapters: 4 },
  { id: '1 Samuel', name: '1 Samuel', apiName: '1 Samuel', chapters: 31 },
  { id: '2 Samuel', name: '2 Samuel', apiName: '2 Samuel', chapters: 24 },
  { id: '1 Kings', name: '1 Reis', apiName: '1 Reis', chapters: 22 },
  { id: '2 Kings', name: '2 Reis', apiName: '2 Reis', chapters: 25 },
  { id: '1 Chronicles', name: '1 Crônicas', apiName: '1 Crônicas', chapters: 29 },
  { id: '2 Chronicles', name: '2 Crônicas', apiName: '2 Crônicas', chapters: 36 },
  { id: 'Ezra', name: 'Esdras', apiName: 'Esdras', chapters: 10 },
  { id: 'Nehemiah', name: 'Neemias', apiName: 'Neemias', chapters: 13 },
  { id: 'Esther', name: 'Ester', apiName: 'Ester', chapters: 10 },
  { id: 'Job', name: 'Jó', apiName: 'Jó', chapters: 42 },
  { id: 'Psalms', name: 'Salmos', apiName: 'Salmos', chapters: 150 },
  { id: 'Proverbs', name: 'Provérbios', apiName: 'Provérbios', chapters: 31 },
  { id: 'Ecclesiastes', name: 'Eclesiastes', apiName: 'Eclesiastes', chapters: 12 },
  { id: 'Song of Solomon', name: 'Cânticos', apiName: 'Cânticos', chapters: 8 },
  { id: 'Isaiah', name: 'Isaías', apiName: 'Isaías', chapters: 66 },
  { id: 'Jeremiah', name: 'Jeremias', apiName: 'Jeremias', chapters: 52 },
  { id: 'Lamentations', name: 'Lamentações', apiName: 'Lamentações', chapters: 5 },
  { id: 'Ezekiel', name: 'Ezequiel', apiName: 'Ezequiel', chapters: 48 },
  { id: 'Daniel', name: 'Daniel', apiName: 'Daniel', chapters: 12 },
  { id: 'Hosea', name: 'Oseias', apiName: 'Oseias', chapters: 14 },
  { id: 'Joel', name: 'Joel', apiName: 'Joel', chapters: 3 },
  { id: 'Amos', name: 'Amós', apiName: 'Amós', chapters: 9 },
  { id: 'Obadiah', name: 'Obadias', apiName: 'Obadias', chapters: 1 },
  { id: 'Jonah', name: 'Jonas', apiName: 'Jonas', chapters: 4 },
  { id: 'Micah', name: 'Miqueias', apiName: 'Miqueias', chapters: 7 },
  { id: 'Nahum', name: 'Naum', apiName: 'Naum', chapters: 3 },
  { id: 'Habakkuk', name: 'Habacuque', apiName: 'Habacuque', chapters: 3 },
  { id: 'Zephaniah', name: 'Sofonias', apiName: 'Sofonias', chapters: 3 },
  { id: 'Haggai', name: 'Ageu', apiName: 'Ageu', chapters: 2 },
  { id: 'Zechariah', name: 'Zacarias', apiName: 'Zacarias', chapters: 14 },
  { id: 'Malachi', name: 'Malaquias', apiName: 'Malaquias', chapters: 4 }
];

export const NEW_TESTAMENT: BookInfo[] = [
  { id: 'Matthew', name: 'Mateus', apiName: 'Mateus', chapters: 28 },
  { id: 'Mark', name: 'Marcos', apiName: 'Marcos', chapters: 16 },
  { id: 'Luke', name: 'Lucas', apiName: 'Lucas', chapters: 24 },
  { id: 'John', name: 'João', apiName: 'João', chapters: 21 },
  { id: 'Acts', name: 'Atos', apiName: 'Atos', chapters: 28 },
  { id: 'Romans', name: 'Romanos', apiName: 'Romanos', chapters: 16 },
  { id: '1 Corinthians', name: '1 Coríntios', apiName: '1 Coríntios', chapters: 16 },
  { id: '2 Corinthians', name: '2 Coríntios', apiName: '2 Coríntios', chapters: 13 },
  { id: 'Galatians', name: 'Gálatas', apiName: 'Gálatas', chapters: 6 },
  { id: 'Ephesians', name: 'Efésios', apiName: 'Efésios', chapters: 6 },
  { id: 'Philippians', name: 'Filipenses', apiName: 'Filipenses', chapters: 4 },
  { id: 'Colossians', name: 'Colossenses', apiName: 'Colossenses', chapters: 4 },
  { id: '1 Thessalonians', name: '1 Tessalonicenses', apiName: '1 Tessalonicenses', chapters: 5 },
  { id: '2 Thessalonians', name: '2 Tessalonicenses', apiName: '2 Tessalonicenses', chapters: 3 },
  { id: '1 Timothy', name: '1 Timóteo', apiName: '1 Timóteo', chapters: 6 },
  { id: '2 Timothy', name: '2 Timóteo', apiName: '2 Timóteo', chapters: 4 },
  { id: 'Titus', name: 'Tito', apiName: 'Tito', chapters: 3 },
  { id: 'Philemon', name: 'Filemom', apiName: 'Filemom', chapters: 1 },
  { id: 'Hebrews', name: 'Hebreus', apiName: 'Hebreus', chapters: 13 },
  { id: 'James', name: 'Tiago', apiName: 'Tiago', chapters: 5 },
  { id: '1 Peter', name: '1 Pedro', apiName: '1 Pedro', chapters: 5 },
  { id: '2 Peter', name: '2 Pedro', apiName: '2 Pedro', chapters: 3 },
  { id: '1 John', name: '1 João', apiName: '1 João', chapters: 5 },
  { id: '2 John', name: '2 João', apiName: '2 João', chapters: 1 },
  { id: '3 John', name: '3 João', apiName: '3 João', chapters: 1 },
  { id: 'Jude', name: 'Judas', apiName: 'Judas', chapters: 1 },
  { id: 'Revelation', name: 'Apocalipse', apiName: 'Apocalipse', chapters: 22 }
];

export const BIBLE_BOOKS: BookInfo[] = [...OLD_TESTAMENT, ...NEW_TESTAMENT];
